# Generated by Django 5.1.6 on 2025-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rol_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
