services:
  - type: web
    name: easycert
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    buildCommand: ""
    startCommand: gunicorn easycert.wsgi:application --workers=2 --threads=2 --timeout=120
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: quirajh@gmail.com
      - key: ADMIN_PASS
        value: admin123
      - key: EMAIL_HOST_USER
        value: juanbaldes6969@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false  # ⚠️ debes configurarla manualmente en el panel de Render (ver abajo)
