# Generated by Django 5.2.5 on 2025-09-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificado_archivo_alter_certificado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('numero_certificado', models.IntegerField(null=True)),
                ('fecha_certificado', models.DateTimeField(null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('campo', models.CharField(max_length=255, null=True)),
                ('valor', models.TextField(null=True)),
            ],
            options={
                'db_table': 'vw_certificado_merge',
                'managed': False,
            },
        ),
    ]
