# Generated by Django 5.2.5 on 2025-09-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_certificado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificado',
        ),
    ]
