# Generated by Django 5.2.5 on 2025-09-04 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_contrato_fecha_generacion_contrato_numero_contrato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('usuario', 'numero_contrato')},
        ),
    ]
