# Generated by Django 5.2.5 on 2025-09-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_contrato_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='obligaciones',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_generacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
