# Generated by Django 5.2.5 on 2025-09-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_contrato_objeto_remove_contrato_obligaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
