# Generated by Django 5.2.6 on 2025-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_contrato_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacion', models.TextField(max_length=255)),
                ('hace_constar', models.TextField(max_length=255)),
                ('introduccion', models.TextField(max_length=255)),
                ('numero_fecha_contrato', models.TextField(max_length=255)),
                ('objeto', models.TextField(max_length=255)),
                ('plazo_ejecucion', models.TextField(max_length=255)),
                ('fecha_inicio_ejecucion', models.TextField(max_length=255)),
                ('fecha_finalizacion', models.TextField(max_length=255)),
                ('valor_pago', models.TextField(max_length=255)),
                ('obligaciones', models.TextField(max_length=255)),
                ('expedicion', models.TextField(max_length=255)),
            ],
        ),
    ]
